import re

VERSION = 3

AUTH_DATA_REGEXP = re.compile("[0-9a-f]{40}[0-9A-Za-z]{24}")

KEY_AUTHORIZED = "authorized"
KEY_MATCH_ACCEPTED = "match.accepted"
KEY_MATCH_NOTIFIED = "match.notified"
KEY_MATCH_WITH = "match.with"
KEY_OAUTH_STATE = "oauth.state"
KEY_OAUTH_TOKEN = "oauth.token"
KEY_SETTINGS_ACTIVE = "settings.active"
KEY_SETTINGS_CAMPUS = "settings.campus"
KEY_SETTINGS_ONLINE = "settings.online"
KEY_TELEGRAM_ID = "telegram.id"
KEY_TELEGRAM_USERNAME = "telegram.username"
KEY_USER_CAMPUS = "user.campus"
KEY_USER_ID = "user.id"
KEY_VERSION = "version"

WEEKDAY_TUESDAY = 1
WEEKDAY_WEDNESDAY = 2

# Callbacks
## Settings
CALLBACK_ACTION_SETTING = "settings"
### Campus
CALLBACK_STEP_CAMPUS = "campus"
CALLBACK_CAMPUS_KAZAN = "kazan"
CALLBACK_CAMPUS_MOSCOW = "moscow"
CALLBACK_CAMPUS_NOVOSIBIRSK = "nsk"
CALLBACK_CHOOSE_KAZAN = "-".join(
    [CALLBACK_ACTION_SETTING, CALLBACK_STEP_CAMPUS, CALLBACK_CAMPUS_KAZAN]
)
CALLBACK_CHOOSE_MOSCOW = "-".join(
    [CALLBACK_ACTION_SETTING, CALLBACK_STEP_CAMPUS, CALLBACK_CAMPUS_MOSCOW]
)
CALLBACK_CHOOSE_NOVOSIBIRSK = "-".join(
    [CALLBACK_ACTION_SETTING, CALLBACK_STEP_CAMPUS, CALLBACK_CAMPUS_NOVOSIBIRSK]
)
### Online
CALLBACK_STEP_ONLINE = "online"
CALLBACK_ONLINE_YES = "yes"
CALLBACK_ONLINE_NO = "no"
CALLBACK_CHOOSE_ONLINE = "-".join(
    [CALLBACK_ACTION_SETTING, CALLBACK_STEP_ONLINE, CALLBACK_ONLINE_YES]
)
CALLBACK_CHOOSE_OFFLINE = "-".join(
    [CALLBACK_ACTION_SETTING, CALLBACK_STEP_ONLINE, CALLBACK_ONLINE_NO]
)
### Active
CALLBACK_STEP_ACTIVE = "active"
CALLBACK_ACTIVE_YES = "yes"
CALLBACK_ACTIVE_NO = "no"
CALLBACK_CHOOSE_ACTIVE = "-".join(
    [CALLBACK_ACTION_SETTING, CALLBACK_STEP_ACTIVE, CALLBACK_ACTIVE_YES]
)
CALLBACK_CHOOSE_INACTIVE = "-".join(
    [CALLBACK_ACTION_SETTING, CALLBACK_STEP_ACTIVE, CALLBACK_ACTIVE_NO]
)
## Match
CALLBACK_ACTION_MATCH = "match"
### Accept
CALLBACK_STEP_ACCEPT = "accept"
CALLBACK_CHOOSE_MATCH = "-".join([CALLBACK_ACTION_MATCH, CALLBACK_STEP_ACCEPT])
